blog/urls.py

from django.conf.urls import url
from . import views 


app_name = 'blog'
urlpatterns = [
    url(r'^$',views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
]

mysite/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog.urls')),
]

blog/models.py
from __future__ import unicode_literals

from django.db import models


# Create your models here.



class Post(models.Model):
    post_title = models.CharField(max_length=50)
    post_content = models.TextField()
    post_date = models.DateTimeField('date published')
    post_author = models.CharField(max_length=50)

    def __str__(self):
        return self.post_title

blog/views.py
from django.shortcuts import render
from django.views import generic

from django.urls import reverse
from .models import Post





# Create your views here.

class IndexView(generic.ListView):
    template_name = 'blog/index.html'
    context_object_name = 'post_list'
    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Post.objects.all().order_by('-id')


class DetailView(generic.DetailView):
    model = Post
    template_name = 'blog/detail.html'

blog/templates/blog/detail.html

<!DOCTYPE html>
<html>
<head>
	<title>Blog - Django</title>
	<meta name="viewport" content="user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1, width=320, height=device-height, target-densitydpi=medium-dpi" />

	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" >
	<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/github-markdown-css/2.4.1/github-markdown.min.css">


	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js" ></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-slider/9.5.4/bootstrap-slider.min.js"></script>

</head>

<body>

	<nav class="navbar navbar-default navbar-fixed-top">
		<div class="container">
			<!-- Brand and toggle get grouped for better mobile display -->
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="/">Blog</a>
			</div>

			<!-- Collect the nav links, forms, and other content for toggling -->
			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">


				<ul class="nav navbar-nav navbar-right">
					<li><a href="https://github.com/kyshel/django-blog">About</a></li>        
				</ul>

			</div><!-- /.navbar-collapse -->
		</div><!-- /.container-fluid -->
	</nav>

	<div class="container" style="padding-top: 70px;">


		<div class="markdown-body">
			<h1 style="text-align:center;">{{ post.post_title }}</h1> 

			{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

			<div>{{ post.post_content | safe }}</div>
			

			<div style="color:#888; float:right; text-align:right;">
			<span>{{ post.post_author }}</span><br>
			<span>{{ post.post_date }}</span> 
			</div>
		</div>

		<hr>


		<footer style="text-align:center;text-color:gray;color:#888;">
			<br>
			<p><a href="http://kyshel.me">Kyshel</a> - 2017 - Powered by <a href="https://www.djangoproject.com/">Django</a></p>
		</footer>


	</div>

	

</body>













blog/templates/blog/index.html

<!DOCTYPE html>
<html>
<head>
	<title>Blog - Django</title>
	<meta name="viewport" content="user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1, width=320, height=device-height, target-densitydpi=medium-dpi" />

	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" >
	<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/github-markdown-css/2.4.1/github-markdown.min.css">


	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js" ></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-slider/9.5.4/bootstrap-slider.min.js"></script>

</head>

<body>

	<nav class="navbar navbar-default navbar-fixed-top">
		<div class="container">
			<!-- Brand and toggle get grouped for better mobile display -->
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="/">Blog</a>
			</div>

			<!-- Collect the nav links, forms, and other content for toggling -->
			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">


				<ul class="nav navbar-nav navbar-right">
					<li><a href="https://github.com/kyshel/django-blog">About</a></li>        
				</ul>

			</div><!-- /.navbar-collapse -->
		</div><!-- /.container-fluid -->
	</nav>

	<div class="container" style="padding-top: 70px;">


		<div class="markdown-body">
			{% if post_list %}
			<ul>
				{% for post in post_list %}
				<li><a href="{% url 'blog:detail' post.id %}">{{ post.post_date | date:"Y/m/d" }}  - {{ post.post_title }}</a></li>
				{% endfor %}
			</ul>
			{% else %}
			<p>No posts are available.</p>
			{% endif %}
		</div>




		<footer style="text-align:center;text-color:gray;color:#888;">
			<br>
			<p><a href="http://kyshel.me">Kyshel</a> - 2017 - Powered by <a href="https://www.djangoproject.com/">Django</a></p>
		</footer>


	</div>

	

</body>